---
# tasks file for collect_host_info
- name: print inventory_hostname
  ansible.builtin.debug:
    var: inventory_hostname

- name: print ansible_hostname
  ansible.builtin.debug:
    var: ansible_hostname

- name: print ansible_fqdn
  ansible.builtin.debug:
    var: ansible_fqdn
